// layout.tsx (Server Component)
import type { Metadata } from "next";
import Sky from "@/components/sky";
import "./globals.css";
import ThemeAudio from "@/components/themeaudio";
// Import client-side audio component

export const metadata: Metadata = {
  title: "CODEFORGE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head />
      <body>
        <Sky /> {/* Background stars */}
        <ThemeAudio/>
        {children}
      </body>
    </html>
  );
}
